apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: "ENV_NAME"
  labels:
    env_name: "ENV_NAME"
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: spark-master