apiVersion: v1
kind: ReplicationController
metadata:
  name: spark-master-controller
  namespace: "ENV_NAME"
  labels:
    env_name: "ENV_NAME"
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        app: spark-master-controller
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: gcr.io/google_containers/spark:1.5.2_v1
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m