apiVersion: v1
kind: ReplicationController
metadata:
  name: spark-worker-controller
  namespace: "ENV_NAME"
  labels:
    env_name: "ENV_NAME"
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker-controller
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark:1.5.2_v1
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m